x-veld:
  code:


services:
  veld_import_rdf:
    build: .
    command: bash /veld/code/scripts/import_rdf.sh
    volumes:
      - ./data/input/:/veld/input/
    networks:
      - veld_fuseki
    environment:
      in_rdf_file: null
      fuseki_server_url: http://veld_run_server
      fuseki_server_port: 3030
      fuseki_dataset_name: null
      fuseki_dataset_type: tdb2
      fuseki_graph_uri: "default"

networks:
  veld_fuseki:

