x-veld:
  code:


services:
  veld_run_server:
    build: .
    entrypoint: bash /veld/code/src/copy_config.sh
    command: /veld/code/fuseki-server
    volumes:
      - ./data/fuseki_data/:/veld/storage/
      - ./data/fuseki_config/:/veld/input/config/
    ports:
      - 3030:3030
    networks:
      - veld_fuseki

networks:
  veld_fuseki:

