x-veld:
  code:


services:
  veld_import_rdf:
    build: .
    command: /veld/code/bin/s-post http://veld_run_server:3030/test3/ default /veld/input/import/pg21000.rdf
    volumes:
      - ./data/input/:/veld/input/import/
    networks:
      - veld_fuseki

networks:
  veld_fuseki:

